development:
  adapter: postgresql
  encoding: unicode
  database: cheap_emails_dev
  pool: 2
  username: joey
  password: joey

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ENV['DATABASE_URL']
  database: ENV['DATABASE']
  username: ENV['USER']
  password: ENV['PASSWORD']
