development:
  adapter: postgresql
  encoding: unicode
  database: cheapdinos_emails
  pool: 2
  username: cheapdinos_emails
  password: ventsoftrench35

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ENV['DATABASE_URL']
  database: ENV['DATABASE']
  username: ENV['USER']
  password: ENV['PASSWORD']
